<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Sa;
use App\Entity\Down;
use App\Repository\Model\SAState;
use \Doctrine\Common\DataFixtures\Purger\ORMPurger;

class DysfunctionnalFunctionnalTest extends WebTestCase
{
    /*
    private $client;
    private $entityManager;

    protected function setUp(): void
    {
        // Create a client and an entity manager to interact with the pages and database
        $this->client = static::createClient();
        $this->entityManager = $this->client->getContainer()->get('doctrine')->getManager();

        // Purge the database before each test
        $purger = new ORMPurger($this->entityManager);
        $purger->purge();
    }

    private function createFunctionalSa(): Sa
    {
        $sa = new Sa();
        $sa->setId(1);
        $sa->setState(SAState::Installed);
        $this->entityManager->persist($sa);
        $this->entityManager->flush();

        return $sa;
    }

    private function createDown($sa, $reason, $temperature = false, $humidity = false, $co2 = false, $microcontroller = false)
    {


        $down = new Down();
        $down->setSa($sa)
        ->setReason($reason)
        ->setTemperature($temperature)
        ->setHumidity($humidity)
        ->setCo2($co2)
        ->setMicrocontroller($microcontroller)
        ->setDate(new \DateTime());


        $sa->setState(SAState::Down);


        $this->entityManager->persist($down);
        $this->entityManager->persist($sa);
        $this->entityManager->flush();

        return $down;
    }


    public function testPageLoad(): void
    {
        // The client try to access to the page
        $this->client->request('GET', '/technicien/sa/panne');

        // Assertions to test if the access succeed
        $this->assertResponseIsSuccessful();
        $this->assertSelectorTextContains('h5.card-title', 'Déclarer un SA dysfonctionnel');
    }

    public function testInsertDown(): void
    {
        $sa = $this->createFunctionalSa();

        $crawler = $this->client->request('GET', '/technicien/sa/panne');

        // Test if the form is displayed
        $this->assertGreaterThan(0, $crawler->filter('form')->count(), 'Le formulaire n\'existe pas.');

        // Awnser to the form
        $form = $crawler->selectButton('Déclarer dysfonctionnel')->form([
            'sa_down[sa]' => $sa->getId(),
            'sa_down[reason]' => 'Température critique',
            'sa_down[temperature]' => true,
        ]);

        $this->client->submit($form);

        // Test if the redirection works correctly
        $this->assertResponseRedirects('#');

        $this->client->followRedirect();

        // Test that the down generated by the form is correctly displayed
        $this->assertSelectorTextContains('tbody', 'Température critique');

        // Check if the SA' state is now "Down"
        $updatedSa = $this->entityManager->getRepository(Sa::class)->find($sa->getId());
        $this->assertEquals(SAState::Down, $updatedSa->getState(), 'Le SA n\'a pas été mis à jour comme dysfonctionnel.');
    }

    public function testShowDown(): void
    {
        // Create a new down sa
        $sa = $this->createFunctionalSa();
        $this->createDown($sa, 'Température élevée', true);

        // Test if the SA is correctly displayed
        $crawler = $this->client->request('GET', '/technicien/sa/panne');
        $this->assertSelectorTextContains('tbody', 'Température élevée');
    }

    public function testRehabilitateSa(): void
    {
        // Create a new functional SA
        $sa = $this->createFunctionalSa();
        $down = $this->createDown($sa, 'Température élevée', true);

        $this->client->request('POST', '/technicien/sa/panne/' . $down->getSa()->getId());
        $this->assertResponseRedirects('/technicien/sa/panne');

        $this->client->followRedirect();
        $this->assertSelectorTextNotContains('tbody', 'Température élevée');

        // Check if the sa' state is now "Functional"
        $updatedSa = $this->entityManager->getRepository(Sa::class)->find($sa->getId());
        $this->assertEquals(SAState::Installed, $updatedSa->getState(), 'Le SA n\'a pas été réhabilité.');
    }

    public function testLastDownSa(): void
    {
        $sa = $this->createFunctionalSa();
        $this->createDown($sa, 'Température élevée', true);

        $crawler = $this->client->request('GET', '/technicien/sa/panne');
        $this->assertSelectorTextContains('tbody', 'Température élevée');
    }

    public function testInsertDownRemovesFromFunctional(): void
    {
        $sa = $this->createFunctionalSa();

        // Use the form to create a new down sa
        $crawler = $this->client->request('GET', '/technicien/sa/panne');
        $form = $crawler->selectButton('Déclarer dysfonctionnel')->form([
            'sa_down[sa]' => $sa->getId(),
            'sa_down[reason]' => 'Humidité excessive',
            'sa_down[humidity]' => true,
        ]);
        $this->client->submit($form);

        $this->assertResponseRedirects('#');

        $this->client->followRedirect();

        // Check if the down exists
        $this->assertSelectorTextContains('tbody', 'Humidité excessive');

        // Check if the selected sa is no longer in the list of functionals sa
        $saRepository = $this->entityManager->getRepository(Sa::class);
        $functionalSa = $saRepository->findBy(['state' => SAState::Installed]);
        $this->assertNotContains($sa, $functionalSa, 'Le SA est toujours marqué comme fonctionnel.');
    }
    */
}
